services:
  app:
    build: .
    ports:
      - "3030:3030"
    environment:
      - DB_HOST=nozomi.proxy.rlwy.net
      - DB_PORT=47316
      - DB_USER=root
      - DB_PASSWORD=ZpmmmwauhGlHxYjaBxywHMPVbfolylBz
      - DB_NAME=railway
    restart: always

  